tmux fixed

diff --git a/home/dot_zshrc b/home/dot_zshrc
--- a/home/dot_zshrc
+++ b/home/dot_zshrc
@@ -12,6 +12,7 @@ export PATH=/usr/local/mysql/bin:$PATH
 # Load before oh-my-zsh
 fpath+=${ZSH_CUSTOM}/plugins/zsh-completions/src
 
+
 # Path to your oh-my-zsh installation.
 export ZSH=$HOME/.oh-my-zsh
 
@@ -25,7 +26,7 @@ ZSH_THEME="powerlevel10k/powerlevel10k"
 # Uncomment the following line if you want to change the command execution time
 # stamp shown in the history command output.
 # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-HIST_STAMPS="yyyy-mm-dd"
+# HIST_STAMPS="yyyy-mm-dd"
 
 ZSH_DISABLE_COMPFIX=true
 
@@ -46,6 +47,15 @@ export RIPGREP_CONFIG_PATH=~/.config/ripgrep/config
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+
+# zshaddhistory() {
+#   # $? contains the exit status of the last command; Commands with exit status 127 have "command not found" error in Zsh
+#   if [[ $? -eq 127 ]]; then
+#     return 1  # Don't add to history
+#   else
+#     return 0  # Add to history
+#   fi
+# }
 
 github-cd() {
 	local dir="${HOME}/src/github.com/$1"
@@ -77,6 +87,11 @@ github-clone-code() {
 	fi
 	code "${dir}"
 }
+
+# NVM
+export NVM_DIR="$HOME/.nvm"
+  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
+  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
 
 # pnpm
 export PNPM_HOME="/Users/lukehooper/Library/pnpm"
